: COLOR: CREATE , 
	DOES> 27 EMIT ." [" @ s>d <# #s #> type ." m" ;

 1 COLOR: BRIGHT      2 COLOR: DIM
30 COLOR: BLACK      40 COLOR: BG-BLACK
31 COLOR: RED        41 COLOR: BG-RED
32 COLOR: GREEN      42 COLOR: BG-GREEN
33 COLOR: YELLOW     43 COLOR: BG-YELLOW
34 COLOR: BLUE       44 COLOR: BG-BLUE
35 COLOR: MAGENTA    45 COLOR: BG-MAGENTA
36 COLOR: CYAN       46 COLOR: BG-CYAN
37 COLOR: WHITE      47 COLOR: BG-WHITE
39 COLOR: FG-DEFAULT 49 COLOR: BG-DEFAULT
